nameOfInputCSVFile: "KM95-28-Dc-1250um.csv"
nameOfExperimentalResultsFile: "data4Optimizer.csv"

# threshold to converge
threshold: 0.01
max_iters: 20000

# sample hyperparameter searchspace
#num_samp_min: [2, 50]          # min number of samples per epoch
num_samp_max: [75, 5000]       # max number of samples per epoch
num_samp_ratio: [0.03,0.1]
num_samp_decay: [0.1, 1]         # decay rate for samples based on best error
resamp_to_samp_ratio: [0.2, 0.9]  # ratio of samples to resamples

# greedy epsilon hyperparameter searchspace
#epsilon_min: [0.0000000001, 0.00000001]         # min greedy epsilon threshold
epsilon_max: [0.00000001, 0.0000001]         # max greedy epsilon threshold
epsilon_growth: [0.000000001, 0.00000001]      # growth rate for epsilon threshold based on best error
epsilon_ratio: [0.0000000001,1]

# List of values to omit during fitting (Added by Drew)
omitValueIndices: [1,2,3,4,5,6,7]

limits:                        
  Ea: [70, 110]
  LnDaa1: [-5,25]
  lnDaa2: [-5,25]
  lnDaa3: [-5,25]
 

  Frac1: [0.001,1]
  Frac2: [0.001,1]










